# Generated by Django 3.2.9 on 2021-12-10 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basketapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='test',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
